### PR TITLE
ML classifications for Summary

### PR DESCRIPTION
**Pull request by hombit**
https://pr219.ztf.snad.space

Questions:

- [ ] What probability threshold to use? Currently all classifications with prob > 10% are shown
- [ ] Maybe we should show the max prob classification only? Or always show it, even if it's prob smaller than threshold?
- [ ] Do we need all these classifiers? Currently we have: 1) Stamp and Light curve for Alerce, 2) binary Fink classifiers for KN, SN and SN Ia, 3) Gaia three class classifier: quasar, galaxy, single star. Do we need Fink's SN Ia vs CC?

### CODE REVIEW

**Comment by pruzhinskaya** [comment]
What probability threshold to use? Currently all classifications with prob > 10% are shown

-- if it is less, you do not show it at all or you are taking about summary only?

Maybe we should show the max prob classification only? Or always show it, even if it's prob smaller than threshold?

-- is it about Summary? In any case I do think that in Summary we should keep only max probability classification

Do we need all these classifiers? Currently we have: 1) Stamp and Light curve for Alerce, 2) binary Fink classifiers for KN, SN and SN Ia, 3) Gaia three class classifier: quasar, galaxy, single star. Do we need Fink's SN Ia vs CC?

-- 1), 3)  Yes, 2) I should check better

**Comment by hombit** [comment]
Everything is about Summary only, there is no other space where you can find it on the page

**Comment by pruzhinskaya** [comment]
About Fink classifiers:

let's keep 

"Ambiguous"
"Kilonova candidate"
"SN candidate"

</body></html>

**Comment by pruzhinskaya** [comment]
https://pr219.ztf.snad.space/dr8/view/758213400002862

Increase radius of cross-match for Alerce - put 30''

изображение

изображение

**Comment by hombit** [comment]
> https://pr219.ztf.snad.space/dr8/view/758213400002862
> 
> Increase radius of cross-match for Alerce - put 30''
> 
> изображение
> 
> изображение

It is fixed along with #223

**Pull request merged**
